version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/htpasswd:/etc/nginx/htpasswd
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/vhosts.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    restart: always 
    logging:
      options:
        max-size: 5M 
    networks:
        - zotabox
    labels:  
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/vhosts.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    restart: always
    logging:
      options:
        max-size: 5M
networks:
  zotabox:
    external: true
